# Generated by Django 5.0.7 on 2024-08-01 14:39

import comments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=comments.models.attachment_image_file_path),
        ),
    ]
